import { Worker, Job } from 'bullmq'
import { connection, JOB_QUEUE_NAME, isQueueEnabled } from './index'
import {
  JOB,
  OrderConfirmationPayload,
  ShippingUpdatePayload,
  OtpEmailPayload,
} from './jobs'
import { prisma } from '../utils/prisma'
import { generateInvoicePdf } from '../services/invoice.service'
import {
  sendOrderConfirmationEmail,
  sendShippingUpdateEmail,
  sendOtpEmail,
} from '../services/email.service'
import { sweepExpiredReservations } from '../services/inventory.service'

/**
 * The order shape the invoice/email services expect. Re-fetched inside the
 * handler rather than carried in the job payload, because a job can run well
 * after it was enqueued and must not act on a stale snapshot.
 */
const orderInclude = {
  items: { include: { product: { include: { images: true } } } },
  address: true,
  user: true,
} as const

/** Audit action marking that the confirmation email already went out. */
const CONFIRMATION_EMAIL_SENT = 'ORDER_CONFIRMATION_EMAIL_SENT'

async function handleOrderConfirmation(data: OrderConfirmationPayload) {
  const order = await prisma.order.findUnique({
    where: { id: data.orderId },
    include: orderInclude,
  })
  if (!order) throw new Error(`Order ${data.orderId} not found`)
  if (!order.user) throw new Error(`Order ${data.orderId} has no user`)

  // Reuse an invoice already generated by a previous attempt — regenerating
  // would upload a duplicate PDF to R2 on every retry.
  let invoiceUrl = order.invoiceUrl
  if (!invoiceUrl) {
    invoiceUrl = await generateInvoicePdf(order as never)
    await prisma.order.update({
      where: { id: order.id },
      data: { invoiceUrl },
    })
  }

  // A retry can land here after the email already went out — a worker crash
  // between send and job completion, or Render reclaiming the instance
  // mid-job. Without this the customer gets a second confirmation.
  // OrderAuditLog is the repo's append-only record for order events, so the
  // marker lives there rather than in a new column.
  const alreadySent = await prisma.orderAuditLog.findFirst({
    where: { orderId: order.id, action: CONFIRMATION_EMAIL_SENT },
    select: { id: true },
  })
  if (alreadySent) {
    console.log(`[Queue] confirmation email already sent for ${order.id}, skipping`)
    return
  }

  await sendOrderConfirmationEmail(order as never, invoiceUrl)

  await prisma.orderAuditLog.create({
    data: {
      orderId: order.id,
      userId: order.userId,
      action: CONFIRMATION_EMAIL_SENT,
      metadata: { invoiceUrl },
    },
  })
}

async function handleShippingUpdate(data: ShippingUpdatePayload) {
  const order = await prisma.order.findUnique({
    where: { id: data.orderId },
    select: { id: true, orderNumber: true, user: { select: { name: true, email: true } } },
  })
  if (!order) throw new Error(`Order ${data.orderId} not found`)
  if (!order.user) throw new Error(`Order ${data.orderId} has no user`)

  await sendShippingUpdateEmail(
    { id: order.id, orderNumber: order.orderNumber, user: order.user },
    {
      ...data.shipping,
      // Dates round-trip through JSON as strings in the job payload.
      expectedBy: data.shipping.expectedBy ? new Date(data.shipping.expectedBy) : null,
    }
  )
}

async function handleOtpEmail(data: OtpEmailPayload) {
  const purpose = data.purpose === 'email-verification' ? 'verification' : 'password-reset'
  await sendOtpEmail(data.email, data.otp, purpose)
}

export async function processJob(job: Job) {
  switch (job.name) {
    case JOB.ORDER_CONFIRMATION:
      return handleOrderConfirmation(job.data as OrderConfirmationPayload)
    case JOB.SHIPPING_UPDATE:
      return handleShippingUpdate(job.data as ShippingUpdatePayload)
    case JOB.OTP_EMAIL:
      return handleOtpEmail(job.data as OtpEmailPayload)
    case JOB.SWEEP_RESERVATIONS:
      return sweepExpiredReservations()
    default:
      throw new Error(`Unknown job: ${job.name}`)
  }
}

let worker: Worker | undefined

/**
 * Start the in-process worker.
 *
 * In-process because Render's free tier has no background-worker service type.
 * The consequence is that the worker stops consuming while the web service is
 * idle-spun-down; jobs resume on the next request that wakes it. Nothing here
 * depends on punctual execution — see docs/deployment.md.
 */
export function startWorker() {
  if (!isQueueEnabled || !connection) {
    console.log('📭 Queue disabled (REDIS_URL unset) — jobs run inline')
    return undefined
  }

  worker = new Worker(JOB_QUEUE_NAME, processJob, {
    connection,
    concurrency: 5,
    // Upstash bills per command and BullMQ polls continuously when idle.
    // A 30s drain delay caps idle polling at ~2 blocking reads/min/worker
    // (~2,880/day), well inside Upstash's free daily command allotment,
    // while costing at most 30s of extra latency on an empty queue.
    drainDelay: 30,
  })

  worker.on('failed', (job, err) => {
    console.error(`[Queue] job ${job?.name} (${job?.id}) failed:`, err.message)
  })

  console.log('👷 Queue worker started')
  return worker
}

export async function stopWorker() {
  await worker?.close()
}
